### ISSUE TITLE
client is not dynamic

### ISSUE THREAD

**Issue by robbyt** [gusdan/django-elasticache#8]
According to the Django docs, `cached_property` will "will persist as long as the instance does". This means it will not dynamically discover changes to the elasticache cluster without the django app restarting.

This is not ideal, since the size of the elasticache cluster may change, and nodes in the cluster may be replaced.

The fix for this would be to add a TTL to the cache, which would require a different memoization scheme for the property.

**Comment by gusdan** [comment]
Yes what is right, but we can save time when we last time discovery cluster and check it each time when we perform new call, but it will give use some gaps in calls, because in additional to getting/setting data  we will discovery cluster. 

In my projects i don't keep long working python process i'm using gunicorn and have max-requests set to 10000 request.

**Comment by robbyt** [comment]
@gusdan Thank you that makes sense.

I agree, setting max-requests and recycling the process is a simpler way to solve this rather than managing a cache TTL.

Please feel free to close this issue- if you wish, I can send a PR that adds a bit of documentation explaining the need for endpoint rediscovery.
